In [ ]:
import pandas as pd

In [ ]:
#Series
s= pd.Series([1,2,3])
np.exp(s)
s+[1000,2000,3000] #elementwise

0    1001
1    2002
2    3003
dtype: int64

In [ ]:
#Series
s= pd.Series([1,2,3])
np.exp(s)
s+[1000] #broadcasting

0    1001
1    1002
2    1003
dtype: int64

In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
#Series
s= pd.Series([1,2,3])
np.exp(s)
s>0

0    True
1    True
2    True
dtype: bool

In [ ]:
s1= pd.Series([1,2,3],index=["akansha","python","pandas"]) #index label

In [ ]:
s1

akansha    1
python     2
pandas     3
dtype: int64

In [ ]:
s1["pandas"]

np.int64(3)

In [ ]:
s1[2]

/tmp/ipykernel_2621/625738788.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[2]

np.int64(3)

In [ ]:
s1.loc["pandas"]

np.int64(3)

In [ ]:
s1.iloc[0:2]

akansha    1
python     2
dtype: int64

In [ ]:
Surprise=pd.Series([1000,200,1002,1003])

In [ ]:
Surprise

0    1000
1     200
2    1002
3    1003
dtype: int64

In [ ]:
surpise_slice= Surprise[0:10]
surpise_slice

0    1000
1     200
2    1002
3    1003
dtype: int64

In [ ]:
try:
  surpsie_slice[0]
except NameError as e:
  print("Encountered Keyerror",e)

Encountered Keyerror name 'surpsie_slice' is not defined

In [ ]:
weight={"Name":85,"Python":45,"darwin":78}

In [ ]:
s1= pd.Series(weight,index=["Python","darwin"])
S2=pd.Series([68,95,85],index=["Name","Python","darwin"])
s3= pd.Series(weight)
print(s3.keys())

S2+s3

Index(['Name', 'Python', 'darwin'], dtype='object')

Name      153
Python    140
darwin    163
dtype: int64

In [ ]:
S2=pd.Series([68,95,85],index=["Name","Python","darwin"])
S4=pd.Series([1000,200,3000])

In [ ]:
S2+S4

Name     NaN
Python   NaN
darwin   NaN
0        NaN
1        NaN
2        NaN
dtype: float64

In [ ]:
pd.Series(52,["life","world","anything"],name="random")

life        52
world       52
anything    52
Name: random, dtype: int64

In [ ]:
dates=pd.date_range("2020/10/28 5:30pm",periods=12,freq="H")
dates

/tmp/ipykernel_2621/592073379.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates=pd.date_range("2020/10/28 5:30pm",periods=12,freq="H")

DatetimeIndex(['2020-10-28 17:30:00', '2020-10-28 18:30:00',
               '2020-10-28 19:30:00', '2020-10-28 20:30:00',
               '2020-10-28 21:30:00', '2020-10-28 22:30:00',
               '2020-10-28 23:30:00', '2020-10-29 00:30:00',
               '2020-10-29 01:30:00', '2020-10-29 02:30:00',
               '2020-10-29 03:30:00', '2020-10-29 04:30:00'],
              dtype='datetime64[ns]', freq='h')

In [ ]:
Temperature ={4.4,5.1,6.1,5.2,2.3,4.5}
temp_Series=pd.Series=(Temperature,dates)
temp_Series

({2.3, 4.4, 4.5, 5.1, 5.2, 6.1},
 DatetimeIndex(['2020-10-28 17:30:00', '2020-10-28 18:30:00',
                '2020-10-28 19:30:00', '2020-10-28 20:30:00',
                '2020-10-28 21:30:00', '2020-10-28 22:30:00',
                '2020-10-28 23:30:00', '2020-10-29 00:30:00',
                '2020-10-29 01:30:00', '2020-10-29 02:30:00',
                '2020-10-29 03:30:00', '2020-10-29 04:30:00'],
               dtype='datetime64[ns]', freq='h'))

In [ ]:
import pandas as pd

In [ ]:
peoDict= pd.DataFrame({
    "Birthday":pd.Series([68,95,85],index=["Name","Python","darwin"]),
    "years":pd.Series([68,95,85],index=["Name","Python","darwin"]),
  "hobby":pd.Series([68,95,85],index=["Name","Python","darwin"]),
    "Dance":pd.Series(["Biking","jumping"],index=["Name","Python"]),
})

In [ ]:
peoDict

        Birthday  years  hobby    Dance
Name          68     68     68   Biking
Python        95     95     95  jumping
darwin        85     85     85      NaN

In [ ]:
peoDict.T

            Name   Python darwin
Birthday      68       95     85
years         68       95     85
hobby         68       95     85
Dance     Biking  jumping    NaN

In [ ]:
dict2=peoDict.stack()

In [ ]:
dict2

Name    Birthday         68
        years            68
        hobby            68
        Dance        Biking
Python  Birthday         95
        years            95
        hobby            95
        Dance       jumping
darwin  Birthday         85
        years            85
        hobby            85
dtype: object

In [ ]:
dict4=peoDict.unstack()

In [ ]:
dict4

Birthday  Name           68
          Python         95
          darwin         85
years     Name           68
          Python         95
          darwin         85
hobby     Name           68
          Python         95
          darwin         85
Dance     Name       Biking
          Python    jumping
          darwin        NaN
dtype: object

In [ ]:
dict5=peoDict.unstack()
dict5

Birthday  Name           68
          Python         95
          darwin         85
years     Name           68
          Python         95
          darwin         85
hobby     Name           68
          Python         95
          darwin         85
Dance     Name       Biking
          Python    jumping
          darwin        NaN
dtype: object